/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.Kanaeru_Back.controller;

import com.example.Kanaeru_Back.model.ApiAuthTermsAgreePost200Response;
import com.example.Kanaeru_Back.model.ApiDailyGoalsCompleteRequest;
import com.example.Kanaeru_Back.model.ApiDailyGoalsCreatePost200Response;
import com.example.Kanaeru_Back.model.ApiDailyGoalsCreatePostRequest;
import com.example.Kanaeru_Back.model.ApiDailyGoalsGet200Response;
import com.example.Kanaeru_Back.model.ApiDailyGoalsReorderRequest;
import com.example.Kanaeru_Back.model.ApiDailyGoalsUpdatePutRequest;
import org.springframework.format.annotation.DateTimeFormat;
import java.time.LocalDate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "DailyGoal", description = "日々の目標関連API")
public interface DailyGoalApi {

    /**
     * POST /api/daily-goals/create : 目標新規作成
     * 日々の目標を新規作成 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiDailyGoalsCreatePostRequest  (required)
     * @return 作成成功 (status code 200)
     */
    @Operation(
        operationId = "apiDailyGoalsCreatePost",
        summary = "目標新規作成",
        description = "日々の目標を新規作成 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "DailyGoal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiDailyGoalsCreatePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/daily-goals/create",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiDailyGoalsCreatePost200Response> apiDailyGoalsCreatePost(
        @Parameter(name = "ApiDailyGoalsCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiDailyGoalsCreatePostRequest apiDailyGoalsCreatePostRequest
    );


    /**
     * PUT /api/daily-goals/{daily_goal_id}/complete : 完了/未完了切替
     * 日々の目標の完了状態を切り替え、実績時間も更新 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param dailyGoalId  (required)
     * @param apiDailyGoalsCompleteRequest  (required)
     * @return 切替成功 (status code 200)
     */
    @Operation(
        operationId = "apiDailyGoalsDailyGoalIdCompletePut",
        summary = "完了/未完了切替",
        description = "日々の目標の完了状態を切り替え、実績時間も更新 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "DailyGoal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "切替成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthTermsAgreePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/daily-goals/{daily_goal_id}/complete",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthTermsAgreePost200Response> apiDailyGoalsDailyGoalIdCompletePut(
        @Parameter(name = "daily_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("daily_goal_id") String dailyGoalId,
        @Parameter(name = "ApiDailyGoalsCompleteRequest", description = "", required = true) @Valid @RequestBody ApiDailyGoalsCompleteRequest apiDailyGoalsCompleteRequest
    );


    /**
     * DELETE /api/daily-goals/{daily_goal_id}/delete : 目標削除（論理削除）
     * 日々の目標を論理削除（DEL_FLG&#x3D;1） responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param dailyGoalId  (required)
     * @return 削除成功 (status code 200)
     */
    @Operation(
        operationId = "apiDailyGoalsDailyGoalIdDeleteDelete",
        summary = "目標削除（論理削除）",
        description = "日々の目標を論理削除（DEL_FLG=1） responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "DailyGoal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthTermsAgreePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/daily-goals/{daily_goal_id}/delete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthTermsAgreePost200Response> apiDailyGoalsDailyGoalIdDeleteDelete(
        @Parameter(name = "daily_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("daily_goal_id") String dailyGoalId
    );


    /**
     * POST /api/daily-goals/{daily_goal_id}/reorder : 並び替え
     * 日々の目標の表示順を変更 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param dailyGoalId  (required)
     * @param apiDailyGoalsReorderRequest  (required)
     * @return 変更成功 (status code 200)
     */
    @Operation(
        operationId = "apiDailyGoalsDailyGoalIdReorderPost",
        summary = "並び替え",
        description = "日々の目標の表示順を変更 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "DailyGoal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "変更成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthTermsAgreePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/daily-goals/{daily_goal_id}/reorder",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthTermsAgreePost200Response> apiDailyGoalsDailyGoalIdReorderPost(
        @Parameter(name = "daily_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("daily_goal_id") String dailyGoalId,
        @Parameter(name = "ApiDailyGoalsReorderRequest", description = "", required = true) @Valid @RequestBody ApiDailyGoalsReorderRequest apiDailyGoalsReorderRequest
    );


    /**
     * PUT /api/daily-goals/{daily_goal_id}/update : 目標更新
     * 日々の目標を更新 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param dailyGoalId  (required)
     * @param apiDailyGoalsUpdatePutRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiDailyGoalsDailyGoalIdUpdatePut",
        summary = "目標更新",
        description = "日々の目標を更新 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "DailyGoal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthTermsAgreePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/daily-goals/{daily_goal_id}/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthTermsAgreePost200Response> apiDailyGoalsDailyGoalIdUpdatePut(
        @Parameter(name = "daily_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("daily_goal_id") String dailyGoalId,
        @Parameter(name = "ApiDailyGoalsUpdatePutRequest", description = "", required = true) @Valid @RequestBody ApiDailyGoalsUpdatePutRequest apiDailyGoalsUpdatePutRequest
    );


    /**
     * GET /api/daily-goals : 週データ取得
     * 指定期間のユーザーの日々の目標一覧を日付ごとに取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @param startDate  (required)
     * @param endDate  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiDailyGoalsGet",
        summary = "週データ取得",
        description = "指定期間のユーザーの日々の目標一覧を日付ごとに取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "DailyGoal" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiDailyGoalsGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/daily-goals",
        produces = "application/json"
    )
    
    ResponseEntity<ApiDailyGoalsGet200Response> apiDailyGoalsGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "startDate", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "startDate", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
        @NotNull @Parameter(name = "endDate", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "endDate", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate
    );

}
