/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.Kanaeru_Back.controller;

import com.example.Kanaeru_Back.model.ApiAuthForgotPasswordPostRequest;
import com.example.Kanaeru_Back.model.ApiAuthLoginPost200Response;
import com.example.Kanaeru_Back.model.ApiAuthLogoutPost200Response;
import com.example.Kanaeru_Back.model.ApiAuthLogoutPostRequest;
import com.example.Kanaeru_Back.model.ApiAuthRegistrationAdminPostRequest;
import com.example.Kanaeru_Back.model.ApiAuthRegistrationUserPost200Response;
import com.example.Kanaeru_Back.model.ApiAuthRegistrationUserPostRequest;
import com.example.Kanaeru_Back.model.ApiAuthResetPasswordPostRequest;
import com.example.Kanaeru_Back.model.ApiAuthUpdatePasswordPutRequest;
import com.example.Kanaeru_Back.model.ApiAvailabilityGet200Response;
import com.example.Kanaeru_Back.model.ApiClientGet200Response;
import com.example.Kanaeru_Back.model.ApiGrossProfitUpdatePut200Response;
import com.example.Kanaeru_Back.model.ApiHomeGet200Response;
import com.example.Kanaeru_Back.model.ApiLargeGoalsChartIdCreatePost200Response;
import com.example.Kanaeru_Back.model.ApiLargeGoalsChartIdCreatePostRequest;
import com.example.Kanaeru_Back.model.ApiLargeGoalsLargeGoalIdDetailGet200Response;
import com.example.Kanaeru_Back.model.ApiMandalaChartsChartIdLargeGoalsGet200Response;
import com.example.Kanaeru_Back.model.ApiMandalaChartsChartIdMainGoalGet200Response;
import com.example.Kanaeru_Back.model.ApiMandalaChartsChartIdUpdatePutRequest;
import com.example.Kanaeru_Back.model.ApiMandalaChartsCreatePostRequest;
import com.example.Kanaeru_Back.model.ApiMandalaChartsCreatePostRequestMainGoal;
import com.example.Kanaeru_Back.model.ApiMandalaChartsGet200Response;
import com.example.Kanaeru_Back.model.ApiMiddleGoalsLargeGoalIdCreatePost200Response;
import com.example.Kanaeru_Back.model.ApiMiddleGoalsLargeGoalIdCreatePostRequest;
import com.example.Kanaeru_Back.model.ApiMiddleGoalsLargeGoalIdGet200Response;
import com.example.Kanaeru_Back.model.ApiMiddleGoalsMiddleGoalIdDetailGet200Response;
import com.example.Kanaeru_Back.model.ApiMiddleGoalsMiddleGoalIdUpdatePutRequest;
import com.example.Kanaeru_Back.model.ApiNetAssetUpdatePut200Response;
import com.example.Kanaeru_Back.model.ApiOperatingProfitUpdatePut200Response;
import com.example.Kanaeru_Back.model.ApiSaleUpdatePut200Response;
import com.example.Kanaeru_Back.model.ApiSettingUpdateAdminPut200Response;
import com.example.Kanaeru_Back.model.ApiSettingUpdateUserPut200Response;
import com.example.Kanaeru_Back.model.ApiSmallGoalsMiddleGoalIdCreatePost200Response;
import com.example.Kanaeru_Back.model.ApiSmallGoalsMiddleGoalIdCreatePostRequest;
import com.example.Kanaeru_Back.model.ApiSmallGoalsMiddleGoalIdGet200Response;
import com.example.Kanaeru_Back.model.ApiSmallGoalsSmallGoalIdCompletePut200Response;
import com.example.Kanaeru_Back.model.ApiSmallGoalsSmallGoalIdDetailGet200Response;
import com.example.Kanaeru_Back.model.ApiSupportGet200Response;
import com.example.Kanaeru_Back.model.ApiSupportReservationAllGet200Response;
import com.example.Kanaeru_Back.model.ApiSupportReservationApprovalPostRequest;
import com.example.Kanaeru_Back.model.ApiSupportReservationGet200Response;
import com.example.Kanaeru_Back.model.ApiSupportReservationPostRequest;
import com.example.Kanaeru_Back.model.ApiSupportSendPostRequest;
import com.example.Kanaeru_Back.model.ApiSupportStreamGet200Response;
import com.example.Kanaeru_Back.model.ApiYearlyBudgetActualGet200Response;
import org.springframework.format.annotation.DateTimeFormat;
import com.example.Kanaeru_Back.model.GrossProfitSchema;
import java.time.LocalDate;
import com.example.Kanaeru_Back.model.NetAssetsSchema;
import com.example.Kanaeru_Back.model.OperatingProfitSchema;
import com.example.Kanaeru_Back.model.SaleSchema;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "認証", description = "認証関連API")
public interface DefaultApi {

    /**
     * DELETE /api/auth/delete : ユーザー削除
     * ユーザー削除時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 削除成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthDeleteDelete",
        summary = "ユーザー削除",
        description = "ユーザー削除時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/auth/delete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiAuthDeleteDelete(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/auth/forgotPassword : パスワード再発行
     * パスワード再発行時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthForgotPasswordPostRequest  (required)
     * @return 再発行成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthForgotPasswordPost",
        summary = "パスワード再発行",
        description = "パスワード再発行時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "再発行成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/forgotPassword",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiAuthForgotPasswordPost(
        @Parameter(name = "ApiAuthForgotPasswordPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthForgotPasswordPostRequest apiAuthForgotPasswordPostRequest
    );


    /**
     * POST /api/auth/login : ログイン
     * ユーザーログイン時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param email  (required)
     * @param passwordHash  (required)
     * @return ログイン成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthLoginPost",
        summary = "ログイン",
        description = "ユーザーログイン時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ログイン成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLoginPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/login",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthLoginPost200Response> apiAuthLoginPost(
        @NotNull @Parameter(name = "email", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "email", required = true) String email,
        @NotNull @Parameter(name = "passwordHash", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "passwordHash", required = true) String passwordHash
    );


    /**
     * POST /api/auth/logout : ログアウト
     * ログアウト時使用、トークン無効化
     *
     * @param apiAuthLogoutPostRequest  (required)
     * @return ログアウト成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthLogoutPost",
        summary = "ログアウト",
        description = "ログアウト時使用、トークン無効化",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "ログアウト成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/logout",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiAuthLogoutPost(
        @Parameter(name = "ApiAuthLogoutPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthLogoutPostRequest apiAuthLogoutPostRequest
    );


    /**
     * POST /api/auth/registration/admin : ユーザー登録(管理者・プラットフォームオーナー)
     * ユーザー登録時使用(管理者・プラットフォームオーナー) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthRegistrationAdminPostRequest  (required)
     * @return 登録成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthRegistrationAdminPost",
        summary = "ユーザー登録(管理者・プラットフォームオーナー)",
        description = "ユーザー登録時使用(管理者・プラットフォームオーナー) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/registration/admin",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiAuthRegistrationAdminPost(
        @Parameter(name = "ApiAuthRegistrationAdminPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthRegistrationAdminPostRequest apiAuthRegistrationAdminPostRequest
    );


    /**
     * POST /api/auth/registration/user : ユーザー登録(一般ユーザー)
     * ユーザー登録時使用(一般ユーザー) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthRegistrationUserPostRequest  (required)
     * @return 登録成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthRegistrationUserPost",
        summary = "ユーザー登録(一般ユーザー)",
        description = "ユーザー登録時使用(一般ユーザー) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "登録成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/registration/user",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiAuthRegistrationUserPost(
        @Parameter(name = "ApiAuthRegistrationUserPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthRegistrationUserPostRequest apiAuthRegistrationUserPostRequest
    );


    /**
     * POST /api/auth/resetPassword : パスワード再設定
     * パスワード再設定時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthResetPasswordPostRequest  (required)
     * @return 再設定成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthResetPasswordPost",
        summary = "パスワード再設定",
        description = "パスワード再設定時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "再設定成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/auth/resetPassword",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiAuthResetPasswordPost(
        @Parameter(name = "ApiAuthResetPasswordPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthResetPasswordPostRequest apiAuthResetPasswordPostRequest
    );


    /**
     * PUT /api/auth/updatePassword : パスワード更新
     * パスワード更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthUpdatePasswordPutRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiAuthUpdatePasswordPut",
        summary = "パスワード更新",
        description = "パスワード更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/auth/updatePassword",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiAuthUpdatePasswordPut(
        @Parameter(name = "ApiAuthUpdatePasswordPutRequest", description = "", required = true) @Valid @RequestBody ApiAuthUpdatePasswordPutRequest apiAuthUpdatePasswordPutRequest
    );


    /**
     * GET /api/availability : サポート画面　予約可能日時取得
     *
     * @param userId  (required)
     * @param date  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiAvailabilityGet",
        summary = "サポート画面　予約可能日時取得",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAvailabilityGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/availability",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAvailabilityGet200Response> apiAvailabilityGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "date", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "date", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date
    );


    /**
     * GET /api/client : クライアントユーザー取得
     * 管理者・プラットフォームオーナーがログイン時に使用 管理者IDが紐づけされているユーザーを取得する responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiClientGet",
        summary = "クライアントユーザー取得",
        description = "管理者・プラットフォームオーナーがログイン時に使用 管理者IDが紐づけされているユーザーを取得する responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "認証" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiClientGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/client",
        produces = "application/json"
    )
    
    ResponseEntity<ApiClientGet200Response> apiClientGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * GET /api/google/authorize : Google認証
     *
     * @param userId  (required)
     * @param returnUrl  (required)
     * @return Google認証ページへリダイレクト (status code 302)
     */
    @Operation(
        operationId = "apiGoogleAuthorizeGet",
        summary = "Google認証",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "302", description = "Google認証ページへリダイレクト")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/google/authorize"
    )
    
    ResponseEntity<Void> apiGoogleAuthorizeGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "returnUrl", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "returnUrl", required = true) String returnUrl
    );


    /**
     * GET /api/google/callback : Google認証コールバック
     *
     * @param state  (required)
     * @param code  (optional)
     * @param error  (optional)
     * @param errorDescription  (optional)
     * @return コールバック処理完了 (status code 200)
     */
    @Operation(
        operationId = "apiGoogleCallbackGet",
        summary = "Google認証コールバック",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "コールバック処理完了")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/google/callback"
    )
    
    ResponseEntity<Void> apiGoogleCallbackGet(
        @NotNull @Parameter(name = "state", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "state", required = true) String state,
        @Parameter(name = "code", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "code", required = false) String code,
        @Parameter(name = "error", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "error", required = false) String error,
        @Parameter(name = "errorDescription", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "errorDescription", required = false) String errorDescription
    );


    /**
     * PUT /api/grossProfit/update : 粗利益更新
     * 粗利益更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param grossProfitSchema  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiGrossProfitUpdatePut",
        summary = "粗利益更新",
        description = "粗利益更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "年次損益計算書更新" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiGrossProfitUpdatePut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/grossProfit/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiGrossProfitUpdatePut200Response> apiGrossProfitUpdatePut(
        @Parameter(name = "GrossProfitSchema", description = "", required = true) @Valid @RequestBody GrossProfitSchema grossProfitSchema
    );


    /**
     * GET /api/home : ホーム画面 初期表示
     * ホーム画面初期表示時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiHomeGet",
        summary = "ホーム画面 初期表示",
        description = "ホーム画面初期表示時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "画面初期表示" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiHomeGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/home",
        produces = "application/json"
    )
    
    ResponseEntity<ApiHomeGet200Response> apiHomeGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/large-goals/{chart_id}/create : 大目標新規作成
     * 新しい大目標を作成 positionは1-8の範囲 goal_type: 1&#x3D;定性/2&#x3D;売上/3&#x3D;粗利益/4&#x3D;営業利益 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param chartId  (required)
     * @param apiLargeGoalsChartIdCreatePostRequest  (required)
     * @return 作成成功 (status code 200)
     */
    @Operation(
        operationId = "apiLargeGoalsChartIdCreatePost",
        summary = "大目標新規作成",
        description = "新しい大目標を作成 positionは1-8の範囲 goal_type: 1=定性/2=売上/3=粗利益/4=営業利益 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "大目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiLargeGoalsChartIdCreatePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/large-goals/{chart_id}/create",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiLargeGoalsChartIdCreatePost200Response> apiLargeGoalsChartIdCreatePost(
        @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("chart_id") String chartId,
        @Parameter(name = "ApiLargeGoalsChartIdCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiLargeGoalsChartIdCreatePostRequest apiLargeGoalsChartIdCreatePostRequest
    );


    /**
     * DELETE /api/large-goals/{large_goal_id}/delete : 大目標削除
     * 大目標を論理削除(DEL_FLG&#x3D;1) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param largeGoalId  (required)
     * @param chartId  (required)
     * @return 削除成功 (status code 200)
     */
    @Operation(
        operationId = "apiLargeGoalsLargeGoalIdDeleteDelete",
        summary = "大目標削除",
        description = "大目標を論理削除(DEL_FLG=1) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "大目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/large-goals/{large_goal_id}/delete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiLargeGoalsLargeGoalIdDeleteDelete(
        @Parameter(name = "large_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("large_goal_id") String largeGoalId,
        @NotNull @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "chart_id", required = true) String chartId
    );


    /**
     * GET /api/large-goals/{large_goal_id}/detail : 大目標詳細取得
     * 大目標の詳細情報と紐づく中目標数を取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param largeGoalId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiLargeGoalsLargeGoalIdDetailGet",
        summary = "大目標詳細取得",
        description = "大目標の詳細情報と紐づく中目標数を取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "大目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiLargeGoalsLargeGoalIdDetailGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/large-goals/{large_goal_id}/detail",
        produces = "application/json"
    )
    
    ResponseEntity<ApiLargeGoalsLargeGoalIdDetailGet200Response> apiLargeGoalsLargeGoalIdDetailGet(
        @Parameter(name = "large_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("large_goal_id") String largeGoalId
    );


    /**
     * PUT /api/large-goals/{large_goal_id}/update : 大目標更新
     * 大目標を更新 positionは1-8の範囲 goal_type: 1&#x3D;定性/2&#x3D;売上/3&#x3D;粗利益/4&#x3D;営業利益 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param largeGoalId  (required)
     * @param apiLargeGoalsChartIdCreatePostRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiLargeGoalsLargeGoalIdUpdatePut",
        summary = "大目標更新",
        description = "大目標を更新 positionは1-8の範囲 goal_type: 1=定性/2=売上/3=粗利益/4=営業利益 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "大目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/large-goals/{large_goal_id}/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiLargeGoalsLargeGoalIdUpdatePut(
        @Parameter(name = "large_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("large_goal_id") String largeGoalId,
        @Parameter(name = "ApiLargeGoalsChartIdCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiLargeGoalsChartIdCreatePostRequest apiLargeGoalsChartIdCreatePostRequest
    );


    /**
     * DELETE /api/mandala-charts/{chart_id}/delete : マンダラチャート削除
     * マンダラチャートを論理削除(DEL_FLG&#x3D;1) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param chartId  (required)
     * @param userId  (required)
     * @return 削除成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsChartIdDeleteDelete",
        summary = "マンダラチャート削除",
        description = "マンダラチャートを論理削除(DEL_FLG=1) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "マンダラチャート" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/mandala-charts/{chart_id}/delete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiMandalaChartsChartIdDeleteDelete(
        @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("chart_id") String chartId,
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * GET /api/mandala-charts/{chart_id}/large-goals : 大目標一覧取得
     * 指定したマンダラチャートの大目標一覧を取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param chartId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsChartIdLargeGoalsGet",
        summary = "大目標一覧取得",
        description = "指定したマンダラチャートの大目標一覧を取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "大目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiMandalaChartsChartIdLargeGoalsGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/mandala-charts/{chart_id}/large-goals",
        produces = "application/json"
    )
    
    ResponseEntity<ApiMandalaChartsChartIdLargeGoalsGet200Response> apiMandalaChartsChartIdLargeGoalsGet(
        @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("chart_id") String chartId
    );


    /**
     * GET /api/mandala-charts/{chart_id}/main-goal : メイン目標取得
     * メイン目標の詳細情報を取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param chartId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsChartIdMainGoalGet",
        summary = "メイン目標取得",
        description = "メイン目標の詳細情報を取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "メイン目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiMandalaChartsChartIdMainGoalGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/mandala-charts/{chart_id}/main-goal",
        produces = "application/json"
    )
    
    ResponseEntity<ApiMandalaChartsChartIdMainGoalGet200Response> apiMandalaChartsChartIdMainGoalGet(
        @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("chart_id") String chartId
    );


    /**
     * PUT /api/mandala-charts/{chart_id}/main-goal/update : メイン目標更新
     * メイン目標を更新 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param chartId  (required)
     * @param apiMandalaChartsCreatePostRequestMainGoal  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsChartIdMainGoalUpdatePut",
        summary = "メイン目標更新",
        description = "メイン目標を更新 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "メイン目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/mandala-charts/{chart_id}/main-goal/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiMandalaChartsChartIdMainGoalUpdatePut(
        @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("chart_id") String chartId,
        @Parameter(name = "ApiMandalaChartsCreatePostRequestMainGoal", description = "", required = true) @Valid @RequestBody ApiMandalaChartsCreatePostRequestMainGoal apiMandalaChartsCreatePostRequestMainGoal
    );


    /**
     * PUT /api/mandala-charts/{chart_id}/update : マンダラチャート更新
     * マンダラチャートを切り替えたりするときに使用 期間を設定してアーカイブができる マンダラチャート情報を更新 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param chartId  (required)
     * @param apiMandalaChartsChartIdUpdatePutRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsChartIdUpdatePut",
        summary = "マンダラチャート更新",
        description = "マンダラチャートを切り替えたりするときに使用 期間を設定してアーカイブができる マンダラチャート情報を更新 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "マンダラチャート" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/mandala-charts/{chart_id}/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiMandalaChartsChartIdUpdatePut(
        @Parameter(name = "chart_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("chart_id") String chartId,
        @Parameter(name = "ApiMandalaChartsChartIdUpdatePutRequest", description = "", required = true) @Valid @RequestBody ApiMandalaChartsChartIdUpdatePutRequest apiMandalaChartsChartIdUpdatePutRequest
    );


    /**
     * POST /api/mandala-charts/create : マンダラチャート新規作成
     * メイン目標を入力されたときにマンダラチャートIDを採番 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiMandalaChartsCreatePostRequest  (required)
     * @return 作成成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsCreatePost",
        summary = "マンダラチャート新規作成",
        description = "メイン目標を入力されたときにマンダラチャートIDを採番 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "マンダラチャート" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/mandala-charts/create",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiMandalaChartsCreatePost(
        @Parameter(name = "ApiMandalaChartsCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiMandalaChartsCreatePostRequest apiMandalaChartsCreatePostRequest
    );


    /**
     * GET /api/mandala-charts : マンダラチャート一覧取得
     * ログインユーザーのマンダラチャート一覧を取得 responseStatusは成功時に1を返却、失敗時は0を返却 アクティブなマンダラチャートを取得 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiMandalaChartsGet",
        summary = "マンダラチャート一覧取得",
        description = "ログインユーザーのマンダラチャート一覧を取得 responseStatusは成功時に1を返却、失敗時は0を返却 アクティブなマンダラチャートを取得 ",
        tags = { "マンダラチャート" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiMandalaChartsGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/mandala-charts",
        produces = "application/json"
    )
    
    ResponseEntity<ApiMandalaChartsGet200Response> apiMandalaChartsGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/middle-goals/{large_goal_id}/create : 中目標新規作成
     * 新しい中目標を作成 positionは1-8の範囲 goal_type: 1&#x3D;定性/2&#x3D;売上/3&#x3D;粗利益/4&#x3D;営業利益 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param largeGoalId  (required)
     * @param apiMiddleGoalsLargeGoalIdCreatePostRequest  (required)
     * @return 作成成功 (status code 200)
     */
    @Operation(
        operationId = "apiMiddleGoalsLargeGoalIdCreatePost",
        summary = "中目標新規作成",
        description = "新しい中目標を作成 positionは1-8の範囲 goal_type: 1=定性/2=売上/3=粗利益/4=営業利益 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "中目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiMiddleGoalsLargeGoalIdCreatePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/middle-goals/{large_goal_id}/create",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiMiddleGoalsLargeGoalIdCreatePost200Response> apiMiddleGoalsLargeGoalIdCreatePost(
        @Parameter(name = "large_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("large_goal_id") String largeGoalId,
        @Parameter(name = "ApiMiddleGoalsLargeGoalIdCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiMiddleGoalsLargeGoalIdCreatePostRequest apiMiddleGoalsLargeGoalIdCreatePostRequest
    );


    /**
     * GET /api/middle-goals/{large_goal_id} : 中目標一覧取得
     * 指定した大目標の中目標一覧を取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param largeGoalId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiMiddleGoalsLargeGoalIdGet",
        summary = "中目標一覧取得",
        description = "指定した大目標の中目標一覧を取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "中目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiMiddleGoalsLargeGoalIdGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/middle-goals/{large_goal_id}",
        produces = "application/json"
    )
    
    ResponseEntity<ApiMiddleGoalsLargeGoalIdGet200Response> apiMiddleGoalsLargeGoalIdGet(
        @Parameter(name = "large_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("large_goal_id") String largeGoalId
    );


    /**
     * DELETE /api/middle-goals/{middle_goal_id}/delete : 中目標削除
     * 中目標を削除 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param middleGoalId  (required)
     * @return 削除成功 (status code 200)
     */
    @Operation(
        operationId = "apiMiddleGoalsMiddleGoalIdDeleteDelete",
        summary = "中目標削除",
        description = "中目標を削除 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "中目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/middle-goals/{middle_goal_id}/delete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiMiddleGoalsMiddleGoalIdDeleteDelete(
        @Parameter(name = "middle_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("middle_goal_id") String middleGoalId
    );


    /**
     * GET /api/middle-goals/{middle_goal_id}/detail : 中目標詳細取得
     * 中目標の詳細情報と紐づく小目標数を取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param middleGoalId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiMiddleGoalsMiddleGoalIdDetailGet",
        summary = "中目標詳細取得",
        description = "中目標の詳細情報と紐づく小目標数を取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "中目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiMiddleGoalsMiddleGoalIdDetailGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/middle-goals/{middle_goal_id}/detail",
        produces = "application/json"
    )
    
    ResponseEntity<ApiMiddleGoalsMiddleGoalIdDetailGet200Response> apiMiddleGoalsMiddleGoalIdDetailGet(
        @Parameter(name = "middle_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("middle_goal_id") String middleGoalId
    );


    /**
     * PUT /api/middle-goals/{middle_goal_id}/update : 中目標更新
     * 中目標を更新 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param middleGoalId  (required)
     * @param apiMiddleGoalsMiddleGoalIdUpdatePutRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiMiddleGoalsMiddleGoalIdUpdatePut",
        summary = "中目標更新",
        description = "中目標を更新 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "中目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/middle-goals/{middle_goal_id}/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiMiddleGoalsMiddleGoalIdUpdatePut(
        @Parameter(name = "middle_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("middle_goal_id") String middleGoalId,
        @Parameter(name = "ApiMiddleGoalsMiddleGoalIdUpdatePutRequest", description = "", required = true) @Valid @RequestBody ApiMiddleGoalsMiddleGoalIdUpdatePutRequest apiMiddleGoalsMiddleGoalIdUpdatePutRequest
    );


    /**
     * PUT /api/netAsset/update : 純資産更新
     * 純資産更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param netAssetsSchema  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiNetAssetUpdatePut",
        summary = "純資産更新",
        description = "純資産更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "年次損益計算書更新" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiNetAssetUpdatePut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/netAsset/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiNetAssetUpdatePut200Response> apiNetAssetUpdatePut(
        @Parameter(name = "NetAssetsSchema", description = "", required = true) @Valid @RequestBody NetAssetsSchema netAssetsSchema
    );


    /**
     * PUT /api/operatingProfit/update : 営業利益更新
     * 営業利益更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param operatingProfitSchema  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiOperatingProfitUpdatePut",
        summary = "営業利益更新",
        description = "営業利益更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "年次損益計算書更新" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiOperatingProfitUpdatePut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/operatingProfit/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiOperatingProfitUpdatePut200Response> apiOperatingProfitUpdatePut(
        @Parameter(name = "OperatingProfitSchema", description = "", required = true) @Valid @RequestBody OperatingProfitSchema operatingProfitSchema
    );


    /**
     * PUT /api/sale/update : 売上更新
     * 売上更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param saleSchema  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiSaleUpdatePut",
        summary = "売上更新",
        description = "売上更新時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "年次損益計算書更新" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSaleUpdatePut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/sale/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiSaleUpdatePut200Response> apiSaleUpdatePut(
        @Parameter(name = "SaleSchema", description = "", required = true) @Valid @RequestBody SaleSchema saleSchema
    );


    /**
     * GET /api/setting/admin : 設定内容取得(管理者・プラットフォームオーナー)
     * 設定内容更新時使用(管理者・プラットフォームオーナー) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSettingAdminGet",
        summary = "設定内容取得(管理者・プラットフォームオーナー)",
        description = "設定内容更新時使用(管理者・プラットフォームオーナー) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "設定変更" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSettingUpdateAdminPut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/setting/admin",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSettingUpdateAdminPut200Response> apiSettingAdminGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * PUT /api/setting/update/admin : 設定内容変更(管理者・プラットフォームオーナー)
     * 設定内容更新時使用(管理者・プラットフォームオーナー) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthRegistrationAdminPostRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiSettingUpdateAdminPut",
        summary = "設定内容変更(管理者・プラットフォームオーナー)",
        description = "設定内容更新時使用(管理者・プラットフォームオーナー) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "設定変更" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSettingUpdateAdminPut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/setting/update/admin",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiSettingUpdateAdminPut200Response> apiSettingUpdateAdminPut(
        @Parameter(name = "ApiAuthRegistrationAdminPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthRegistrationAdminPostRequest apiAuthRegistrationAdminPostRequest
    );


    /**
     * PUT /api/setting/update/user : 設定内容変更(一般ユーザー)
     * 設定内容更新時使用(一般ユーザー) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param apiAuthRegistrationUserPostRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiSettingUpdateUserPut",
        summary = "設定内容変更(一般ユーザー)",
        description = "設定内容更新時使用(一般ユーザー) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "設定変更" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSettingUpdateUserPut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/setting/update/user",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiSettingUpdateUserPut200Response> apiSettingUpdateUserPut(
        @Parameter(name = "ApiAuthRegistrationUserPostRequest", description = "", required = true) @Valid @RequestBody ApiAuthRegistrationUserPostRequest apiAuthRegistrationUserPostRequest
    );


    /**
     * GET /api/setting/user : 設定内容取得(一般ユーザー)
     * 設定内容更新時使用(一般ユーザー) responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSettingUserGet",
        summary = "設定内容取得(一般ユーザー)",
        description = "設定内容更新時使用(一般ユーザー) responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "設定変更" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSettingUpdateUserPut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/setting/user",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSettingUpdateUserPut200Response> apiSettingUserGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/small-goals/{middle_goal_id}/create : 小目標新規作成
     *
     * @param middleGoalId  (required)
     * @param apiSmallGoalsMiddleGoalIdCreatePostRequest  (required)
     * @return 作成成功 (status code 200)
     */
    @Operation(
        operationId = "apiSmallGoalsMiddleGoalIdCreatePost",
        summary = "小目標新規作成",
        tags = { "小目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSmallGoalsMiddleGoalIdCreatePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/small-goals/{middle_goal_id}/create",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiSmallGoalsMiddleGoalIdCreatePost200Response> apiSmallGoalsMiddleGoalIdCreatePost(
        @Parameter(name = "middle_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("middle_goal_id") String middleGoalId,
        @Parameter(name = "ApiSmallGoalsMiddleGoalIdCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiSmallGoalsMiddleGoalIdCreatePostRequest apiSmallGoalsMiddleGoalIdCreatePostRequest
    );


    /**
     * GET /api/small-goals/{middle_goal_id} : 小目標一覧取得
     *
     * @param middleGoalId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSmallGoalsMiddleGoalIdGet",
        summary = "小目標一覧取得",
        tags = { "小目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSmallGoalsMiddleGoalIdGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/small-goals/{middle_goal_id}",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSmallGoalsMiddleGoalIdGet200Response> apiSmallGoalsMiddleGoalIdGet(
        @Parameter(name = "middle_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("middle_goal_id") String middleGoalId
    );


    /**
     * PUT /api/small-goals/{small_goal_id}/complete : 小目標完了/未完了切替
     *
     * @param smallGoalId  (required)
     * @return 切替成功 (status code 200)
     */
    @Operation(
        operationId = "apiSmallGoalsSmallGoalIdCompletePut",
        summary = "小目標完了/未完了切替",
        tags = { "小目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "切替成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSmallGoalsSmallGoalIdCompletePut200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/small-goals/{small_goal_id}/complete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSmallGoalsSmallGoalIdCompletePut200Response> apiSmallGoalsSmallGoalIdCompletePut(
        @Parameter(name = "small_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("small_goal_id") String smallGoalId
    );


    /**
     * DELETE /api/small-goals/{small_goal_id}/delete : 小目標削除
     *
     * @param smallGoalId  (required)
     * @return 削除成功 (status code 200)
     */
    @Operation(
        operationId = "apiSmallGoalsSmallGoalIdDeleteDelete",
        summary = "小目標削除",
        tags = { "小目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "削除成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/small-goals/{small_goal_id}/delete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiSmallGoalsSmallGoalIdDeleteDelete(
        @Parameter(name = "small_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("small_goal_id") String smallGoalId
    );


    /**
     * GET /api/small-goals/{small_goal_id}/detail : 小目標詳細取得
     *
     * @param smallGoalId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSmallGoalsSmallGoalIdDetailGet",
        summary = "小目標詳細取得",
        tags = { "小目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSmallGoalsSmallGoalIdDetailGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/small-goals/{small_goal_id}/detail",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSmallGoalsSmallGoalIdDetailGet200Response> apiSmallGoalsSmallGoalIdDetailGet(
        @Parameter(name = "small_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("small_goal_id") String smallGoalId
    );


    /**
     * PUT /api/small-goals/{small_goal_id}/update : 小目標更新
     *
     * @param smallGoalId  (required)
     * @param apiSmallGoalsMiddleGoalIdCreatePostRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "apiSmallGoalsSmallGoalIdUpdatePut",
        summary = "小目標更新",
        tags = { "小目標" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/small-goals/{small_goal_id}/update",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiSmallGoalsSmallGoalIdUpdatePut(
        @Parameter(name = "small_goal_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("small_goal_id") String smallGoalId,
        @Parameter(name = "ApiSmallGoalsMiddleGoalIdCreatePostRequest", description = "", required = true) @Valid @RequestBody ApiSmallGoalsMiddleGoalIdCreatePostRequest apiSmallGoalsMiddleGoalIdCreatePostRequest
    );


    /**
     * GET /api/support : サポート画面 初期表示
     *
     * @param userId  (required)
     * @param selecteId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportGet",
        summary = "サポート画面 初期表示",
        tags = { "画面初期表示" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSupportGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/support",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSupportGet200Response> apiSupportGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "selecteId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "selecteId", required = true) String selecteId
    );


    /**
     * GET /api/support/read : サポート画面 メッセージ既読
     *
     * @param senderId  (required)
     * @param recipientId  (required)
     * @param content  (required)
     * @param messageSeq  (required)
     * @return 既読成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportReadGet",
        summary = "サポート画面 メッセージ既読",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "既読成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSupportGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/support/read",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSupportGet200Response> apiSupportReadGet(
        @NotNull @Parameter(name = "senderId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "senderId", required = true) String senderId,
        @NotNull @Parameter(name = "recipientId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "recipientId", required = true) String recipientId,
        @NotNull @Parameter(name = "content", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "content", required = true) String content,
        @NotNull @Parameter(name = "messageSeq", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "messageSeq", required = true) Integer messageSeq
    );


    /**
     * GET /api/support/reservation/all : サポート画面 予約履歴(全件)
     *
     * @param userId  (required)
     * @param selecteId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportReservationAllGet",
        summary = "サポート画面 予約履歴(全件)",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSupportReservationAllGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/support/reservation/all",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSupportReservationAllGet200Response> apiSupportReservationAllGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "selecteId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "selecteId", required = true) String selecteId
    );


    /**
     * POST /api/support/reservation/approval : サポート画面 予約承諾
     *
     * @param apiSupportReservationApprovalPostRequest  (required)
     * @return 承諾成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportReservationApprovalPost",
        summary = "サポート画面 予約承諾",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "承諾成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/support/reservation/approval",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiSupportReservationApprovalPost(
        @Parameter(name = "ApiSupportReservationApprovalPostRequest", description = "", required = true) @Valid @RequestBody ApiSupportReservationApprovalPostRequest apiSupportReservationApprovalPostRequest
    );


    /**
     * GET /api/support/reservation : サポート画面 予約履歴
     *
     * @param userId  (required)
     * @param selecteId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportReservationGet",
        summary = "サポート画面 予約履歴",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSupportReservationGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/support/reservation",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSupportReservationGet200Response> apiSupportReservationGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "selecteId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "selecteId", required = true) String selecteId
    );


    /**
     * POST /api/support/reservation : サポート画面 予約作成
     *
     * @param apiSupportReservationPostRequest  (required)
     * @return 作成成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportReservationPost",
        summary = "サポート画面 予約作成",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/support/reservation",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiSupportReservationPost(
        @Parameter(name = "ApiSupportReservationPostRequest", description = "", required = true) @Valid @RequestBody ApiSupportReservationPostRequest apiSupportReservationPostRequest
    );


    /**
     * POST /api/support/reservation/reject : サポート画面 予約拒否
     *
     * @param apiSupportReservationApprovalPostRequest  (required)
     * @return 拒否成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportReservationRejectPost",
        summary = "サポート画面 予約拒否",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "拒否成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthRegistrationUserPost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/support/reservation/reject",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthRegistrationUserPost200Response> apiSupportReservationRejectPost(
        @Parameter(name = "ApiSupportReservationApprovalPostRequest", description = "", required = true) @Valid @RequestBody ApiSupportReservationApprovalPostRequest apiSupportReservationApprovalPostRequest
    );


    /**
     * POST /api/support/send : サポート画面 メッセージ送信
     *
     * @param apiSupportSendPostRequest  (required)
     * @return 送信成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportSendPost",
        summary = "サポート画面 メッセージ送信",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "送信成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSupportGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/support/send",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiSupportGet200Response> apiSupportSendPost(
        @Parameter(name = "ApiSupportSendPostRequest", description = "", required = true) @Valid @RequestBody ApiSupportSendPostRequest apiSupportSendPostRequest
    );


    /**
     * GET /api/support/stream : サポート画面 メッセージ受信
     *
     * @param userId  (required)
     * @return 受信成功 (status code 200)
     */
    @Operation(
        operationId = "apiSupportStreamGet",
        summary = "サポート画面 メッセージ受信",
        tags = { "サポート画面" },
        responses = {
            @ApiResponse(responseCode = "200", description = "受信成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSupportStreamGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/support/stream",
        produces = "application/json"
    )
    
    ResponseEntity<ApiSupportStreamGet200Response> apiSupportStreamGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * GET /api/yearlyBudgetActual : 予実管理(年次)画面 初期表示
     * ロードマップ設定画面初期表示時使用 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "apiYearlyBudgetActualGet",
        summary = "予実管理(年次)画面 初期表示",
        description = "ロードマップ設定画面初期表示時使用 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "画面初期表示" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiYearlyBudgetActualGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/yearlyBudgetActual",
        produces = "application/json"
    )
    
    ResponseEntity<ApiYearlyBudgetActualGet200Response> apiYearlyBudgetActualGet(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );

}
