/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.Kanaeru_Back.controller;

import com.example.Kanaeru_Back.model.ApiAuthTermsAgreePost200Response;
import com.example.Kanaeru_Back.model.GetSlackUserMapping200Response;
import com.example.Kanaeru_Back.model.SlackUserMappingRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Slack連携", description = "Slack連携関連API（SLACK_USER_MAPPINGS テーブル）")
public interface SlackApi {

    /**
     * GET /api/slack/user-mapping : Slack ユーザーID取得
     * ユーザーの Slack User ID（Member ID）を取得 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId  (required)
     * @return 取得成功 (status code 200)
     */
    @Operation(
        operationId = "getSlackUserMapping",
        summary = "Slack ユーザーID取得",
        description = "ユーザーの Slack User ID（Member ID）を取得 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "Slack連携" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = GetSlackUserMapping200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/slack/user-mapping",
        produces = "application/json"
    )
    
    ResponseEntity<GetSlackUserMapping200Response> getSlackUserMapping(
        @NotNull @Parameter(name = "userId", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * PUT /api/slack/user-mapping : Slack ユーザーID登録・更新
     * ユーザーの Slack User ID を SLACK_USER_MAPPINGS テーブルに upsert responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param slackUserMappingRequest  (required)
     * @return 登録・更新成功 (status code 200)
     */
    @Operation(
        operationId = "updateSlackUserMapping",
        summary = "Slack ユーザーID登録・更新",
        description = "ユーザーの Slack User ID を SLACK_USER_MAPPINGS テーブルに upsert responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "Slack連携" },
        responses = {
            @ApiResponse(responseCode = "200", description = "登録・更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthTermsAgreePost200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/slack/user-mapping",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiAuthTermsAgreePost200Response> updateSlackUserMapping(
        @Parameter(name = "SlackUserMappingRequest", description = "", required = true) @Valid @RequestBody SlackUserMappingRequest slackUserMappingRequest
    );

}
