/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.Kanaeru_Back.controller;

import com.example.Kanaeru_Back.model.ApiSlackEventsPost200Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "SlackEvent", description = "Slack Event API（Slack Bot用）")
public interface SlackEventApi {

    /**
     * POST /api/slack/events : Slack Event受信
     * SlackからのEvent API通知を受け取る 1. Signing Secretで正規リクエスト検証 2. url_verificationチャレンジ対応（初回のみ） 3. app_mentionイベント時に目標をDBに登録し返信 【重要】リクエストボディは署名検証のためraw bodyで受け取ること 
     *
     * @param xSlackSignature Slackの署名（v0&#x3D;...形式） (required)
     * @param xSlackRequestTimestamp リクエストのUNIXタイムスタンプ (required)
     * @param body  (required)
     * @return 受信成功 (status code 200)
     *         or 署名検証失敗 (status code 400)
     */
    @Operation(
        operationId = "apiSlackEventsPost",
        summary = "Slack Event受信",
        description = "SlackからのEvent API通知を受け取る 1. Signing Secretで正規リクエスト検証 2. url_verificationチャレンジ対応（初回のみ） 3. app_mentionイベント時に目標をDBに登録し返信 【重要】リクエストボディは署名検証のためraw bodyで受け取ること ",
        tags = { "SlackEvent" },
        responses = {
            @ApiResponse(responseCode = "200", description = "受信成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiSlackEventsPost200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "署名検証失敗")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/slack/events",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiSlackEventsPost200Response> apiSlackEventsPost(
        @NotNull @Parameter(name = "X-Slack-Signature", description = "Slackの署名（v0=...形式）", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Slack-Signature", required = true) String xSlackSignature,
        @NotNull @Parameter(name = "X-Slack-Request-Timestamp", description = "リクエストのUNIXタイムスタンプ", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "X-Slack-Request-Timestamp", required = true) String xSlackRequestTimestamp,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody String body
    );

}
