/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.Kanaeru_Back.controller;

import com.example.Kanaeru_Back.model.ApiAuthLogoutPost200Response;
import com.example.Kanaeru_Back.model.ApiStripeSubscriptionCancelPost200Response;
import com.example.Kanaeru_Back.model.ApiStripeSubscriptionCreatePost500Response;
import com.example.Kanaeru_Back.model.ApiStripeSubscriptionGet200Response;
import com.example.Kanaeru_Back.model.ApiWebhooksStripePost200Response;
import com.example.Kanaeru_Back.model.ApiWebhooksStripePost400Response;
import com.example.Kanaeru_Back.model.CreateSubscriptionRequest;
import com.example.Kanaeru_Back.model.CreateSubscriptionResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Stripe決済", description = "Stripe決済関連API")
public interface StripeApi {

    /**
     * POST /api/stripe/subscription/cancel/incomplete : サブスクリプション解約（未完了）
     * 未完了のサブスクリプションを解約する responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId ユーザーID (required)
     * @return 解約成功 (status code 200)
     *         or 未完了のサブスクリプションが見つからない (status code 404)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "apiStripeSubscriptionCancelIncompletePost",
        summary = "サブスクリプション解約（未完了）",
        description = "未完了のサブスクリプションを解約する responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "Stripe決済" },
        responses = {
            @ApiResponse(responseCode = "200", description = "解約成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "未完了のサブスクリプションが見つからない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiStripeSubscriptionCreatePost500Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/stripe/subscription/cancel/incomplete",
        produces = "application/json"
    )
    
    ResponseEntity<ApiAuthLogoutPost200Response> apiStripeSubscriptionCancelIncompletePost(
        @NotNull @Parameter(name = "userId", description = "ユーザーID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/stripe/subscription/cancel : サブスクリプション解約
     * サブスクリプションを期間終了時に解約する 即時解約ではなく、現在の請求期間終了まで利用可能 responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId ユーザーID (required)
     * @return 解約予約成功 (status code 200)
     *         or アクティブなサブスクリプションが見つからない (status code 404)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "apiStripeSubscriptionCancelPost",
        summary = "サブスクリプション解約",
        description = "サブスクリプションを期間終了時に解約する 即時解約ではなく、現在の請求期間終了まで利用可能 responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "Stripe決済" },
        responses = {
            @ApiResponse(responseCode = "200", description = "解約予約成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiStripeSubscriptionCancelPost200Response.class))
            }),
            @ApiResponse(responseCode = "404", description = "アクティブなサブスクリプションが見つからない", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiStripeSubscriptionCreatePost500Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/stripe/subscription/cancel",
        produces = "application/json"
    )
    
    ResponseEntity<ApiStripeSubscriptionCancelPost200Response> apiStripeSubscriptionCancelPost(
        @NotNull @Parameter(name = "userId", description = "ユーザーID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/stripe/subscription/create : サブスクリプション作成
     * 有料プラン選択時、Stripe CustomerとSubscriptionを作成しClientSecretを返す フロントのStep3→Step4移行時に呼ばれる responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId ユーザーID (required)
     * @param createSubscriptionRequest  (required)
     * @return 作成成功 (status code 200)
     *         or 既にアクティブなサブスクリプションが存在 (status code 409)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "apiStripeSubscriptionCreatePost",
        summary = "サブスクリプション作成",
        description = "有料プラン選択時、Stripe CustomerとSubscriptionを作成しClientSecretを返す フロントのStep3→Step4移行時に呼ばれる responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "Stripe決済" },
        responses = {
            @ApiResponse(responseCode = "200", description = "作成成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateSubscriptionResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "既にアクティブなサブスクリプションが存在", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiAuthLogoutPost200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiStripeSubscriptionCreatePost500Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/stripe/subscription/create",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<CreateSubscriptionResponse> apiStripeSubscriptionCreatePost(
        @NotNull @Parameter(name = "userId", description = "ユーザーID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId,
        @Parameter(name = "CreateSubscriptionRequest", description = "", required = true) @Valid @RequestBody CreateSubscriptionRequest createSubscriptionRequest
    );


    /**
     * GET /api/stripe/subscription/ : 現在のサブスクリプション情報取得
     * ユーザーの現在のサブスクリプション状態を取得する サブスクリプションがない場合はnullを返す responseStatusは成功時に1を返却、失敗時は0を返却 
     *
     * @param userId ユーザーID (required)
     * @return 取得成功 (status code 200)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "apiStripeSubscriptionGet",
        summary = "現在のサブスクリプション情報取得",
        description = "ユーザーの現在のサブスクリプション状態を取得する サブスクリプションがない場合はnullを返す responseStatusは成功時に1を返却、失敗時は0を返却 ",
        tags = { "Stripe決済" },
        responses = {
            @ApiResponse(responseCode = "200", description = "取得成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiStripeSubscriptionGet200Response.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiStripeSubscriptionCreatePost500Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/stripe/subscription/",
        produces = "application/json"
    )
    
    ResponseEntity<ApiStripeSubscriptionGet200Response> apiStripeSubscriptionGet(
        @NotNull @Parameter(name = "userId", description = "ユーザーID", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "userId", required = true) String userId
    );


    /**
     * POST /api/webhooks/stripe : StripeWebhook受信
     * Stripeからの非同期通知を受け取る Stripeダッシュボード「開発者」→「Webhook」でこのURLを登録すること 対応イベント:   - invoice.paid（支払い完了 → サブスク有効化/更新）   - invoice.payment_failed（支払い失敗）   - customer.subscription.deleted（サブスクリプション終了 → 無効化） 【重要】リクエストボディは署名検証のためraw bodyで受け取ること 
     *
     * @param stripeSignature Stripeの署名（署名検証に使用） (required)
     * @param body  (required)
     * @return 受信成功 (status code 200)
     *         or 署名検証失敗 (status code 400)
     */
    @Operation(
        operationId = "apiWebhooksStripePost",
        summary = "StripeWebhook受信",
        description = "Stripeからの非同期通知を受け取る Stripeダッシュボード「開発者」→「Webhook」でこのURLを登録すること 対応イベント:   - invoice.paid（支払い完了 → サブスク有効化/更新）   - invoice.payment_failed（支払い失敗）   - customer.subscription.deleted（サブスクリプション終了 → 無効化） 【重要】リクエストボディは署名検証のためraw bodyで受け取ること ",
        tags = { "Stripe決済" },
        responses = {
            @ApiResponse(responseCode = "200", description = "受信成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiWebhooksStripePost200Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "署名検証失敗", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiWebhooksStripePost400Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/webhooks/stripe",
        produces = "application/json",
        consumes = "application/json"
    )
    
    ResponseEntity<ApiWebhooksStripePost200Response> apiWebhooksStripePost(
        @NotNull @Parameter(name = "Stripe-Signature", description = "Stripeの署名（署名検証に使用）", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Stripe-Signature", required = true) String stripeSignature,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody String body
    );

}
